/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAuthorizedRouteImport } from './routes/notAuthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVentasManualesRouteImport } from './routes/_authenticated/ventas-manuales'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated/productos'
import { Route as AuthenticatedOrdenesRouteImport } from './routes/_authenticated/ordenes'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCombosRouteImport } from './routes/_authenticated/combos'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'

const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/notAuthorized',
  path: '/notAuthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVentasManualesRoute =
  AuthenticatedVentasManualesRouteImport.update({
    id: '/ventas-manuales',
    path: '/ventas-manuales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdenesRoute = AuthenticatedOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCombosRoute = AuthenticatedCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/notAuthorized': typeof NotAuthorizedRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/combos': typeof AuthenticatedCombosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/ordenes': typeof AuthenticatedOrdenesRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas-manuales': typeof AuthenticatedVentasManualesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notAuthorized': typeof NotAuthorizedRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/combos': typeof AuthenticatedCombosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/ordenes': typeof AuthenticatedOrdenesRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas-manuales': typeof AuthenticatedVentasManualesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/notAuthorized': typeof NotAuthorizedRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/combos': typeof AuthenticatedCombosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/ordenes': typeof AuthenticatedOrdenesRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ventas-manuales': typeof AuthenticatedVentasManualesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notAuthorized'
    | '/banners'
    | '/combos'
    | '/dashboard'
    | '/finanzas'
    | '/ordenes'
    | '/productos'
    | '/stock'
    | '/usuarios'
    | '/ventas-manuales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notAuthorized'
    | '/banners'
    | '/combos'
    | '/dashboard'
    | '/finanzas'
    | '/ordenes'
    | '/productos'
    | '/stock'
    | '/usuarios'
    | '/ventas-manuales'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/notAuthorized'
    | '/_authenticated/banners'
    | '/_authenticated/combos'
    | '/_authenticated/dashboard'
    | '/_authenticated/finanzas'
    | '/_authenticated/ordenes'
    | '/_authenticated/productos'
    | '/_authenticated/stock'
    | '/_authenticated/usuarios'
    | '/_authenticated/ventas-manuales'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notAuthorized': {
      id: '/notAuthorized'
      path: '/notAuthorized'
      fullPath: '/notAuthorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ventas-manuales': {
      id: '/_authenticated/ventas-manuales'
      path: '/ventas-manuales'
      fullPath: '/ventas-manuales'
      preLoaderRoute: typeof AuthenticatedVentasManualesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordenes': {
      id: '/_authenticated/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof AuthenticatedOrdenesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/combos': {
      id: '/_authenticated/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AuthenticatedCombosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedCombosRoute: typeof AuthenticatedCombosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedOrdenesRoute: typeof AuthenticatedOrdenesRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentasManualesRoute: typeof AuthenticatedVentasManualesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedCombosRoute: AuthenticatedCombosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedOrdenesRoute: AuthenticatedOrdenesRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentasManualesRoute: AuthenticatedVentasManualesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
