/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAuthorizedRouteImport } from './routes/notAuthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVentasManualesRouteImport } from './routes/_authenticated/ventas-manuales'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTiposProductoRouteImport } from './routes/_authenticated/tipos-producto'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSeccionesLandingRouteImport } from './routes/_authenticated/secciones-landing'
import { Route as AuthenticatedPublicidadNavbarRouteImport } from './routes/_authenticated/publicidad-navbar'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated/productos'
import { Route as AuthenticatedOrdenesRouteImport } from './routes/_authenticated/ordenes'
import { Route as AuthenticatedNewsletterRouteImport } from './routes/_authenticated/newsletter'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCuponesRouteImport } from './routes/_authenticated/cupones'
import { Route as AuthenticatedCombosRouteImport } from './routes/_authenticated/combos'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'

const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/notAuthorized',
  path: '/notAuthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVentasManualesRoute =
  AuthenticatedVentasManualesRouteImport.update({
    id: '/ventas-manuales',
    path: '/ventas-manuales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiposProductoRoute =
  AuthenticatedTiposProductoRouteImport.update({
    id: '/tipos-producto',
    path: '/tipos-producto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeccionesLandingRoute =
  AuthenticatedSeccionesLandingRouteImport.update({
    id: '/secciones-landing',
    path: '/secciones-landing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPublicidadNavbarRoute =
  AuthenticatedPublicidadNavbarRouteImport.update({
    id: '/publicidad-navbar',
    path: '/publicidad-navbar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdenesRoute = AuthenticatedOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsletterRoute = AuthenticatedNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuponesRoute = AuthenticatedCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCombosRoute = AuthenticatedCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/notAuthorized': typeof NotAuthorizedRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/blog': typeof AuthenticatedBlogRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/combos': typeof AuthenticatedCombosRoute
  '/cupones': typeof AuthenticatedCuponesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/newsletter': typeof AuthenticatedNewsletterRoute
  '/ordenes': typeof AuthenticatedOrdenesRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/publicidad-navbar': typeof AuthenticatedPublicidadNavbarRoute
  '/secciones-landing': typeof AuthenticatedSeccionesLandingRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tipos-producto': typeof AuthenticatedTiposProductoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas-manuales': typeof AuthenticatedVentasManualesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notAuthorized': typeof NotAuthorizedRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/blog': typeof AuthenticatedBlogRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/combos': typeof AuthenticatedCombosRoute
  '/cupones': typeof AuthenticatedCuponesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/newsletter': typeof AuthenticatedNewsletterRoute
  '/ordenes': typeof AuthenticatedOrdenesRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/publicidad-navbar': typeof AuthenticatedPublicidadNavbarRoute
  '/secciones-landing': typeof AuthenticatedSeccionesLandingRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tipos-producto': typeof AuthenticatedTiposProductoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas-manuales': typeof AuthenticatedVentasManualesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/notAuthorized': typeof NotAuthorizedRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/blog': typeof AuthenticatedBlogRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/combos': typeof AuthenticatedCombosRoute
  '/_authenticated/cupones': typeof AuthenticatedCuponesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/newsletter': typeof AuthenticatedNewsletterRoute
  '/_authenticated/ordenes': typeof AuthenticatedOrdenesRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/publicidad-navbar': typeof AuthenticatedPublicidadNavbarRoute
  '/_authenticated/secciones-landing': typeof AuthenticatedSeccionesLandingRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/tipos-producto': typeof AuthenticatedTiposProductoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ventas-manuales': typeof AuthenticatedVentasManualesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notAuthorized'
    | '/ajustes'
    | '/banners'
    | '/blog'
    | '/categorias'
    | '/combos'
    | '/cupones'
    | '/dashboard'
    | '/finanzas'
    | '/newsletter'
    | '/ordenes'
    | '/productos'
    | '/publicidad-navbar'
    | '/secciones-landing'
    | '/stock'
    | '/tipos-producto'
    | '/usuarios'
    | '/ventas-manuales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notAuthorized'
    | '/ajustes'
    | '/banners'
    | '/blog'
    | '/categorias'
    | '/combos'
    | '/cupones'
    | '/dashboard'
    | '/finanzas'
    | '/newsletter'
    | '/ordenes'
    | '/productos'
    | '/publicidad-navbar'
    | '/secciones-landing'
    | '/stock'
    | '/tipos-producto'
    | '/usuarios'
    | '/ventas-manuales'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/notAuthorized'
    | '/_authenticated/ajustes'
    | '/_authenticated/banners'
    | '/_authenticated/blog'
    | '/_authenticated/categorias'
    | '/_authenticated/combos'
    | '/_authenticated/cupones'
    | '/_authenticated/dashboard'
    | '/_authenticated/finanzas'
    | '/_authenticated/newsletter'
    | '/_authenticated/ordenes'
    | '/_authenticated/productos'
    | '/_authenticated/publicidad-navbar'
    | '/_authenticated/secciones-landing'
    | '/_authenticated/stock'
    | '/_authenticated/tipos-producto'
    | '/_authenticated/usuarios'
    | '/_authenticated/ventas-manuales'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notAuthorized': {
      id: '/notAuthorized'
      path: '/notAuthorized'
      fullPath: '/notAuthorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ventas-manuales': {
      id: '/_authenticated/ventas-manuales'
      path: '/ventas-manuales'
      fullPath: '/ventas-manuales'
      preLoaderRoute: typeof AuthenticatedVentasManualesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tipos-producto': {
      id: '/_authenticated/tipos-producto'
      path: '/tipos-producto'
      fullPath: '/tipos-producto'
      preLoaderRoute: typeof AuthenticatedTiposProductoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secciones-landing': {
      id: '/_authenticated/secciones-landing'
      path: '/secciones-landing'
      fullPath: '/secciones-landing'
      preLoaderRoute: typeof AuthenticatedSeccionesLandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publicidad-navbar': {
      id: '/_authenticated/publicidad-navbar'
      path: '/publicidad-navbar'
      fullPath: '/publicidad-navbar'
      preLoaderRoute: typeof AuthenticatedPublicidadNavbarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordenes': {
      id: '/_authenticated/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof AuthenticatedOrdenesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/newsletter': {
      id: '/_authenticated/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof AuthenticatedNewsletterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cupones': {
      id: '/_authenticated/cupones'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof AuthenticatedCuponesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/combos': {
      id: '/_authenticated/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AuthenticatedCombosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCombosRoute: typeof AuthenticatedCombosRoute
  AuthenticatedCuponesRoute: typeof AuthenticatedCuponesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedNewsletterRoute: typeof AuthenticatedNewsletterRoute
  AuthenticatedOrdenesRoute: typeof AuthenticatedOrdenesRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedPublicidadNavbarRoute: typeof AuthenticatedPublicidadNavbarRoute
  AuthenticatedSeccionesLandingRoute: typeof AuthenticatedSeccionesLandingRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTiposProductoRoute: typeof AuthenticatedTiposProductoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentasManualesRoute: typeof AuthenticatedVentasManualesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedBlogRoute: AuthenticatedBlogRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCombosRoute: AuthenticatedCombosRoute,
  AuthenticatedCuponesRoute: AuthenticatedCuponesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedNewsletterRoute: AuthenticatedNewsletterRoute,
  AuthenticatedOrdenesRoute: AuthenticatedOrdenesRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedPublicidadNavbarRoute: AuthenticatedPublicidadNavbarRoute,
  AuthenticatedSeccionesLandingRoute: AuthenticatedSeccionesLandingRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTiposProductoRoute: AuthenticatedTiposProductoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentasManualesRoute: AuthenticatedVentasManualesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
